name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: |
          sudo apt update
          sudo apt install nodejs
          cargo install wasm-pack
      - name: Build
        run: npm run build:release
      - name: Run tests
        run: npm run test
